name: Create Localization Help Issue (Single Job)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to compare to (last by default)'
        type: string
        default: 'afea18f6f1cda5c8db8e31dfec8edf7e04624f90'
        required: true
      template:
        description: 'Custom YAML template for Markdown (if needed)'
        type: string
        default: '/scripts/template.yml'
        required: true
      disable-mentions:
        description: 'Print mentions as string'
        type: choice
        options: [ 'True', 'False' ]
        default: 'False'
        required: true
      js-patch:
        description: 'use git diff for JSON templates (for large repos)'
        required: true
        type: choice
        options: [ 'True', 'False' ]
        default: 'False'

jobs:
  create-localization-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Run Python Action from external repo
        id: run_action
        uses: Knutschbert/create-localization-issue@main
        with:
          # base-dir: ""
          # base-file: ""
          branch: ${{ github.ref }}
          commit: ${{ github.event.inputs.commit }}
          # maintainers: ""
          template: ${{ github.event.inputs.template }}
          disable-mentions: ${{ github.event.inputs.disable-mentions }}
          js-patch: ${{ github.event.inputs.js-patch }}

      # - name: Print outputs
      #   run: echo "Title ${{ steps.run_action.outputs.issue-title }} Comments ${{ toJSON(steps.run_action.outputs.comments) }}"
      - name: Create GitHub issue
        id: create_issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.run_action.outputs.issue-title }}
          body: ${{ steps.run_action.outputs.issue-body }}
          labels: |
            localization
            automated
            help wanted

      - name: Install GitHub CLI
        uses: cli/cli-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comments in a loop
        env:
          COMMENTS: ${{ steps.run_action.outputs.comments }}
          ISSUE_NUMBER: ${{ steps.create_issue.outputs.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$COMMENTS" | jq -c '.[]' | while read -r comment; do
            echo "Creating comment: $comment"
            gh api repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
              --method POST \
              --header "Authorization: Bearer $GITHUB_TOKEN" \
              --header "Accept: application/vnd.github.v3+json" \
              --field body="$comment"
          done