name: Manual Trigger - Use External Action

on:
  workflow_dispatch:

jobs:
  call-external-python-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your own repo
        uses: actions/checkout@v4

      - name: Run Python Action from external repo
        id: run_action
        uses: Knutschbert/create-localization-issue@main  # Or better: use a commit SHA or tag
        with:
          # base_dir: ""
          # base_file: ""
          branch: "loc_wf"
          commit: "afea18f6f1cda5c8db8e31dfec8edf7e04624f90"
          # maintainers: ""
          # template: ""
      - name: Print outputs
        run: echo "One ${{ steps.run_action.outputs.output-one }} Two ${{ steps.run_action.outputs.output-two }}"
