name: Localization Update request

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to compare to (last by default)'
        type: string
        default: 'HEAD^'
        required: true
  # push:
  #   paths:
  #     - 'assets/base/assets/localization/**'

jobs:
  check-localization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install python dependencies
        run: pip3 install PyGithub pycountry

      - name: Run localization diff script
        run: python .github/scripts/detect_localization_changes.py ${{ github.ref }} ${{ github.event.inputs.commit }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
